"""
Solar Flare Forecasting Model
==============================
Predicts the probability of a flare occurring in the next N minutes
using features engineered from SoLEXS lightcurve data.

This is the ML-based forecasting component of the hackathon solution.
"""
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for Windows
import matplotlib.pyplot as plt
from astropy.io import fits
from astropy.time import Time
from scipy.ndimage import uniform_filter1d
from scipy.signal import find_peaks
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import (
    classification_report, roc_auc_score, precision_recall_curve,
    roc_curve, confusion_matrix, f1_score, average_precision_score
)
from sklearn.preprocessing import StandardScaler
import xgboost as xgb
import os
import glob
import json
import pickle
import warnings
warnings.filterwarnings('ignore')


# =================================================================
# CONFIGURATION
# =================================================================
DATASET_DIR = "dataset"
CATALOG_FILE = "master_flare_catalog.json"

# Feature engineering
HISTORY_WINDOW = 1800    # 30 minutes of history (in seconds)
STEP_SIZE = 60           # Extract features every 60 seconds (1 min)

# Prediction horizons (seconds)
HORIZONS = {
    "15min": 900,
    "30min": 1800,
}

# Use 15min as primary target
PRIMARY_HORIZON = "15min"

# Class imbalance
POSITIVE_WEIGHT = 10  # Weight for flare samples (flares are rare)


# =================================================================
# DATA LOADING
# =================================================================
def find_lc_file(folder_path):
    """Find lightcurve file, handling nested PRADAN structure."""
    search_roots = [folder_path]
    for item in os.listdir(folder_path):
        nested = os.path.join(folder_path, item)
        if os.path.isdir(nested) and item.startswith("AL1_"):
            search_roots.insert(0, nested)

    for root in search_roots:
        for det in ["SDD2", "SDD1"]:
            sdd_dir = os.path.join(root, det)
            if not os.path.isdir(sdd_dir):
                continue
            lc_files = glob.glob(os.path.join(sdd_dir, "*.lc.gz")) + \
                       glob.glob(os.path.join(sdd_dir, "*.lc"))
            if lc_files:
                return lc_files[0], det
    return None, None


def load_all_data():
    """Load all available lightcurve data into a single time-series."""
    folders = sorted([f for f in os.listdir(DATASET_DIR)
                      if os.path.isdir(os.path.join(DATASET_DIR, f)) and f.startswith("AL1_")])

    all_times = []
    all_counts = []

    for folder in folders:
        folder_path = os.path.join(DATASET_DIR, folder)
        lc_path, det = find_lc_file(folder_path)
        if not lc_path:
            continue

        hdul = fits.open(lc_path)
        data = hdul[1].data
        header = hdul[1].header

        time_raw = data["TIME"].copy()
        counts = data["COUNTS"].copy()

        # Replace NaN with 0
        counts = np.nan_to_num(counts, nan=0.0)

        all_times.append(time_raw)
        all_counts.append(counts)

        mjd_ref = header["MJDREFI"] + header["MJDREFF"]
        tstart = Time(mjd_ref + header["TSTART"] / 86400.0, format="mjd")
        print(f"  Loaded {tstart.datetime.strftime('%Y-%m-%d')} ({det}): {len(counts)} points")

        hdul.close()

    # Concatenate all days
    times = np.concatenate(all_times)
    counts = np.concatenate(all_counts)

    print(f"\nTotal data points: {len(counts)} ({len(counts)/86400:.1f} days)")
    return times, counts


# =================================================================
# LABEL GENERATION
# =================================================================
def load_flare_catalog():
    """Load the master flare catalog generated by detect_flares.py."""
    with open(CATALOG_FILE, 'r') as f:
        data = json.load(f)
    return data["catalog"]


def create_labels(times, catalog, horizon_sec):
    """
    Create binary labels: 1 if a flare starts within the next 'horizon_sec' seconds.

    For each time step t:
      label[t] = 1  if any flare START is within [t, t + horizon_sec]
      label[t] = 0  otherwise

    IMPORTANT: We label based on flare START time (not peak).
    This means we're predicting the ONSET, giving maximum lead time.
    """
    labels = np.zeros(len(times), dtype=np.int32)

    flare_starts = [f["start_time"] for f in catalog]
    flare_classes = [f.get("flare_class", "B") for f in catalog]

    for start_t, fclass in zip(flare_starts, flare_classes):
        # Find time steps where this flare is within the horizon
        mask = (times >= start_t - horizon_sec) & (times < start_t)
        labels[mask] = 1

    return labels


def create_multiclass_labels(times, catalog, horizon_sec):
    """
    Multi-class labels:
      0 = no flare expected
      1 = B/C class flare expected
      2 = M/X class flare expected
    """
    labels = np.zeros(len(times), dtype=np.int32)

    for flare in catalog:
        start_t = flare["start_time"]
        fclass = flare.get("flare_class", "B")

        mask = (times >= start_t - horizon_sec) & (times < start_t)

        if fclass in ("M", "X"):
            labels[mask] = 2
        else:
            labels[mask] = np.maximum(labels[mask], 1)

    return labels


# =================================================================
# FEATURE ENGINEERING
# =================================================================
def engineer_features(times, counts, step_size=STEP_SIZE, window=HISTORY_WINDOW):
    """
    Extract features from sliding windows of the lightcurve.

    For each time step t, we look at the past 'window' seconds
    and compute statistical, derivative, and spectral features.

    Returns: feature_matrix (N x F), feature_names, sample_indices
    """
    n = len(counts)

    # Pre-compute some useful arrays
    # Smooth at different scales
    smooth_10s = uniform_filter1d(counts, size=10)
    smooth_30s = uniform_filter1d(counts, size=30)
    smooth_60s = uniform_filter1d(counts, size=60)
    smooth_300s = uniform_filter1d(counts, size=300)

    # First derivative (rate of change)
    deriv = np.gradient(smooth_30s)

    # Second derivative (acceleration)
    deriv2 = np.gradient(deriv)

    # Log counts (useful for log-scale patterns)
    log_counts = np.log1p(counts)  # log(1 + x) to handle zeros

    features_list = []
    sample_indices = []

    # Step through the data
    for i in range(window, n, step_size):
        # Window of raw data
        win = counts[i - window:i]
        win_smooth = smooth_30s[i - window:i]
        win_deriv = deriv[i - window:i]
        win_deriv2 = deriv2[i - window:i]
        win_log = log_counts[i - window:i]

        # Sub-windows (recent vs earlier)
        recent_5min = counts[max(0, i - 300):i]
        recent_1min = counts[max(0, i - 60):i]
        earlier = counts[i - window:max(0, i - 300)]

        feat = {}

        # --- Basic statistics (full window) ---
        feat["mean"] = np.mean(win)
        feat["std"] = np.std(win)
        feat["min"] = np.min(win)
        feat["max"] = np.max(win)
        feat["median"] = np.median(win)
        feat["skewness"] = _skewness(win)
        feat["kurtosis"] = _kurtosis(win)
        feat["iqr"] = np.percentile(win, 75) - np.percentile(win, 25)
        feat["p90"] = np.percentile(win, 90)
        feat["p99"] = np.percentile(win, 99)

        # --- Log-scale statistics ---
        feat["log_mean"] = np.mean(win_log)
        feat["log_std"] = np.std(win_log)
        feat["log_max"] = np.max(win_log)

        # --- Current value features ---
        feat["current"] = smooth_30s[i - 1]
        feat["current_raw"] = counts[i - 1]
        feat["current_log"] = log_counts[i - 1]

        # --- Multi-scale smoothing ratios ---
        feat["ratio_10_300"] = smooth_10s[i-1] / max(smooth_300s[i-1], 0.1)
        feat["ratio_30_300"] = smooth_30s[i-1] / max(smooth_300s[i-1], 0.1)
        feat["ratio_60_300"] = smooth_60s[i-1] / max(smooth_300s[i-1], 0.1)

        # --- Derivative features (rate of change) ---
        feat["deriv_mean"] = np.mean(win_deriv)
        feat["deriv_max"] = np.max(win_deriv)
        feat["deriv_min"] = np.min(win_deriv)
        feat["deriv_std"] = np.std(win_deriv)
        feat["deriv_current"] = deriv[i - 1]

        # Recent derivatives (last 5 min)
        recent_deriv = deriv[max(0, i - 300):i]
        feat["deriv_recent_mean"] = np.mean(recent_deriv)
        feat["deriv_recent_max"] = np.max(recent_deriv)

        # --- Acceleration (2nd derivative) ---
        feat["accel_mean"] = np.mean(win_deriv2)
        feat["accel_max"] = np.max(win_deriv2)
        feat["accel_current"] = deriv2[i - 1]

        # --- Trend features ---
        # Is flux rising or falling?
        feat["recent_vs_earlier_mean"] = np.mean(recent_5min) / max(np.mean(earlier), 0.1) if len(earlier) > 0 else 1.0
        feat["recent_vs_earlier_max"] = np.max(recent_5min) / max(np.max(earlier), 0.1) if len(earlier) > 0 else 1.0
        feat["last_1min_vs_mean"] = np.mean(recent_1min) / max(np.mean(win), 0.1)

        # Linear trend (slope) over the window
        if len(win_smooth) > 1:
            x = np.arange(len(win_smooth))
            coeffs = np.polyfit(x, win_smooth, 1)
            feat["trend_slope"] = coeffs[0]
            feat["trend_intercept"] = coeffs[1]
        else:
            feat["trend_slope"] = 0
            feat["trend_intercept"] = 0

        # --- Background estimation ---
        bg = np.percentile(win, 30)
        feat["background"] = bg
        feat["current_over_bg"] = smooth_30s[i-1] / max(bg, 0.1)
        feat["max_over_bg"] = np.max(win) / max(bg, 0.1)

        # --- Pre-flare indicators ---
        # "Precursor heating": slow, steady rise before impulsive phase
        # Split window into 6 segments, check if each is higher than previous
        n_segments = 6
        seg_len = len(win) // n_segments
        if seg_len > 0:
            seg_means = [np.mean(win[j*seg_len:(j+1)*seg_len]) for j in range(n_segments)]
            rising_count = sum(1 for j in range(1, n_segments) if seg_means[j] > seg_means[j-1])
            feat["monotonic_rise_score"] = rising_count / (n_segments - 1)
            feat["seg_ratio_last_first"] = seg_means[-1] / max(seg_means[0], 0.1)
        else:
            feat["monotonic_rise_score"] = 0
            feat["seg_ratio_last_first"] = 1

        # --- Variability / oscillation features ---
        # Count zero-crossings of derivative (oscillation indicator)
        sign_changes = np.diff(np.sign(win_deriv))
        feat["zero_crossings"] = np.count_nonzero(sign_changes)

        # Coefficient of variation
        feat["cv"] = np.std(win) / max(np.mean(win), 0.1)

        # --- Peak features ---
        peaks, properties = find_peaks(win_smooth, height=bg * 2, distance=30)
        feat["n_peaks"] = len(peaks)
        feat["max_peak_height"] = max(properties["peak_heights"]) if len(peaks) > 0 else 0

        # --- Time-based features ---
        # Not all hours are equal for solar activity
        seconds_of_day = (times[i] - times[i] // 86400 * 86400)
        feat["hour_sin"] = np.sin(2 * np.pi * seconds_of_day / 86400)
        feat["hour_cos"] = np.cos(2 * np.pi * seconds_of_day / 86400)

        features_list.append(feat)
        sample_indices.append(i)

    # Convert to DataFrame
    df = pd.DataFrame(features_list)
    feature_names = list(df.columns)

    print(f"  Engineered {len(df)} samples with {len(feature_names)} features each")
    return df.values, feature_names, np.array(sample_indices)


def _skewness(x):
    """Compute skewness."""
    m = np.mean(x)
    s = np.std(x)
    if s == 0:
        return 0
    return np.mean(((x - m) / s) ** 3)


def _kurtosis(x):
    """Compute kurtosis."""
    m = np.mean(x)
    s = np.std(x)
    if s == 0:
        return 0
    return np.mean(((x - m) / s) ** 4) - 3


# =================================================================
# MODEL TRAINING
# =================================================================
def train_model(X_train, y_train, X_val, y_val, feature_names):
    """Train an XGBoost classifier for flare prediction."""

    # Calculate class weight
    n_pos = y_train.sum()
    n_neg = len(y_train) - n_pos
    scale_pos_weight = n_neg / max(n_pos, 1) * 0.5  # Moderate upweighting

    print(f"\n  Training samples: {len(y_train)} (pos={n_pos}, neg={n_neg})")
    print(f"  Validation samples: {len(y_val)} (pos={y_val.sum()}, neg={len(y_val)-y_val.sum()})")
    print(f"  Scale pos weight: {scale_pos_weight:.1f}")

    model = xgb.XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        scale_pos_weight=scale_pos_weight,
        min_child_weight=5,
        subsample=0.8,
        colsample_bytree=0.8,
        reg_alpha=0.1,
        reg_lambda=1.0,
        eval_metric="aucpr",
        random_state=42,
        verbosity=0,
    )

    model.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )

    return model


# =================================================================
# EVALUATION
# =================================================================
def evaluate_model(model, X_test, y_test, times_test, catalog, feature_names, horizon_name):
    """Comprehensive evaluation of the forecasting model."""

    y_prob = model.predict_proba(X_test)[:, 1]
    y_pred = (y_prob >= 0.5).astype(int)

    print(f"\n{'='*60}")
    print(f"EVALUATION RESULTS ({horizon_name} horizon)")
    print(f"{'='*60}")

    # Basic metrics
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["No Flare", "Flare"]))

    # AUC scores
    if y_test.sum() > 0 and (1 - y_test).sum() > 0:
        roc_auc = roc_auc_score(y_test, y_prob)
        pr_auc = average_precision_score(y_test, y_prob)
        print(f"ROC-AUC: {roc_auc:.4f}")
        print(f"PR-AUC:  {pr_auc:.4f}")
    else:
        roc_auc = 0
        pr_auc = 0
        print("Cannot compute AUC (only one class in test set)")

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)
    tn, fp, fn, tp = cm.ravel()
    print(f"\nConfusion Matrix:")
    print(f"  True Positives:  {tp}")
    print(f"  True Negatives:  {tn}")
    print(f"  False Positives: {fp} (false alarms)")
    print(f"  False Negatives: {fn} (missed flares)")

    tpr = tp / max(tp + fn, 1)
    far = fp / max(fp + tn, 1)
    print(f"\n  True Positive Rate:  {tpr:.4f}")
    print(f"  False Alarm Rate:    {far:.4f}")

    # Lead time analysis
    lead_times = compute_lead_times(y_prob, times_test, catalog, threshold=0.5)

    # Feature importance
    plot_feature_importance(model, feature_names, horizon_name)

    # ROC and PR curves
    plot_curves(y_test, y_prob, horizon_name, roc_auc, pr_auc)

    return {
        "roc_auc": roc_auc,
        "pr_auc": pr_auc,
        "tpr": tpr,
        "far": far,
        "tp": tp, "tn": tn, "fp": fp, "fn": fn,
        "lead_times": lead_times,
    }


def compute_lead_times(y_prob, times_test, catalog, threshold=0.5):
    """
    For each flare in the catalog, compute how many minutes BEFORE
    the flare start the model first triggered an alert.

    This is the KEY metric judges care about.
    """
    print(f"\n--- Lead Time Analysis ---")

    lead_times = []

    for flare in catalog:
        flare_start = flare["start_time"]
        flare_id = flare.get("flare_id", "?")
        flare_class = flare.get("flare_class", "?")

        # Find predictions in the window before this flare
        pre_flare_mask = (times_test >= flare_start - 1800) & (times_test < flare_start)
        if pre_flare_mask.sum() == 0:
            continue

        pre_flare_probs = y_prob[pre_flare_mask]
        pre_flare_times = times_test[pre_flare_mask]

        # Find first alert (first time prob exceeds threshold)
        alert_mask = pre_flare_probs >= threshold
        if alert_mask.sum() > 0:
            first_alert_idx = np.where(alert_mask)[0][0]
            first_alert_time = pre_flare_times[first_alert_idx]
            lead_time_sec = flare_start - first_alert_time
            lead_time_min = lead_time_sec / 60.0
            lead_times.append(lead_time_min)
            print(f"  {flare_id} ({flare_class}-class): Alert {lead_time_min:.1f} min before flare")
        else:
            print(f"  {flare_id} ({flare_class}-class): MISSED (no alert triggered)")
            lead_times.append(0)

    if lead_times:
        valid = [lt for lt in lead_times if lt > 0]
        if valid:
            print(f"\n  Average lead time: {np.mean(valid):.1f} minutes")
            print(f"  Median lead time:  {np.median(valid):.1f} minutes")
            print(f"  Min lead time:     {np.min(valid):.1f} minutes")
            print(f"  Max lead time:     {np.max(valid):.1f} minutes")
            print(f"  Flares with alert: {len(valid)}/{len(lead_times)}")

    return lead_times


# =================================================================
# VISUALIZATION
# =================================================================
def plot_feature_importance(model, feature_names, horizon_name):
    """Plot top 20 most important features."""
    importance = model.feature_importances_
    indices = np.argsort(importance)[-20:]

    fig, ax = plt.subplots(figsize=(10, 8))
    ax.barh(range(len(indices)), importance[indices], color="#1976D2")
    ax.set_yticks(range(len(indices)))
    ax.set_yticklabels([feature_names[i] for i in indices], fontsize=9)
    ax.set_xlabel("Feature Importance (Gain)", fontsize=11)
    ax.set_title(f"Top 20 Features - {horizon_name} Forecast", fontsize=13, fontweight="bold")
    ax.grid(True, alpha=0.3, axis="x")
    plt.tight_layout()
    plt.savefig(f"feature_importance_{horizon_name}.png", dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: feature_importance_{horizon_name}.png")


def plot_curves(y_test, y_prob, horizon_name, roc_auc, pr_auc):
    """Plot ROC and Precision-Recall curves."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    # ROC curve
    if roc_auc > 0:
        fpr, tpr, _ = roc_curve(y_test, y_prob)
        ax1.plot(fpr, tpr, color="#1976D2", linewidth=2, label=f"AUC = {roc_auc:.3f}")
        ax1.plot([0, 1], [0, 1], "k--", alpha=0.3, label="Random")
        ax1.set_xlabel("False Positive Rate")
        ax1.set_ylabel("True Positive Rate")
        ax1.set_title(f"ROC Curve - {horizon_name}", fontweight="bold")
        ax1.legend()
        ax1.grid(True, alpha=0.3)

    # Precision-Recall curve
    if pr_auc > 0:
        prec, rec, _ = precision_recall_curve(y_test, y_prob)
        ax2.plot(rec, prec, color="#E65100", linewidth=2, label=f"AP = {pr_auc:.3f}")
        baseline = y_test.sum() / len(y_test)
        ax2.axhline(y=baseline, color="k", linestyle="--", alpha=0.3, label=f"Baseline = {baseline:.3f}")
        ax2.set_xlabel("Recall")
        ax2.set_ylabel("Precision")
        ax2.set_title(f"Precision-Recall Curve - {horizon_name}", fontweight="bold")
        ax2.legend()
        ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(f"eval_curves_{horizon_name}.png", dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: eval_curves_{horizon_name}.png")


def plot_predictions_timeline(times_test, y_test, y_prob, catalog, horizon_name):
    """Plot prediction probabilities over time with actual flares marked."""
    # Convert to hours from start
    t0 = times_test[0]
    hours = (times_test - t0) / 3600.0

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16, 8), sharex=True)

    # Panel 1: Prediction probability
    ax1.fill_between(hours, 0, y_prob, alpha=0.4, color="#1976D2", label="Flare probability")
    ax1.axhline(y=0.5, color="red", linestyle="--", alpha=0.5, label="Alert threshold (0.5)")
    ax1.set_ylabel("Probability", fontsize=11)
    ax1.set_title(f"Flare Forecast Probabilities - {horizon_name} horizon", fontsize=13, fontweight="bold")
    ax1.legend(loc="upper right", fontsize=9)
    ax1.set_ylim(0, 1.05)
    ax1.grid(True, alpha=0.3)

    # Panel 2: Actual labels
    ax2.fill_between(hours, 0, y_test, alpha=0.4, color="#4CAF50", step="mid", label="Actual (flare imminent)")
    ax2.set_ylabel("Actual Label", fontsize=11)
    ax2.set_xlabel("Hours from start of test set", fontsize=11)
    ax2.set_title("Ground Truth", fontsize=13, fontweight="bold")
    ax2.legend(loc="upper right", fontsize=9)
    ax2.set_ylim(-0.05, 1.5)
    ax2.grid(True, alpha=0.3)

    # Mark flare peaks
    for flare in catalog:
        peak_t = flare["peak_time"]
        if peak_t >= times_test[0] and peak_t <= times_test[-1]:
            peak_h = (peak_t - t0) / 3600.0
            fclass = flare.get("flare_class", "?")
            for ax in [ax1, ax2]:
                ax.axvline(x=peak_h, color="red", alpha=0.4, linewidth=1)
            ax1.annotate(f'{fclass}', xy=(peak_h, 0.95), fontsize=8, fontweight="bold",
                        color="red", ha="center")

    plt.tight_layout()
    plt.savefig(f"forecast_timeline_{horizon_name}.png", dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  Saved: forecast_timeline_{horizon_name}.png")


# =================================================================
# MAIN PIPELINE
# =================================================================
def main():
    print("[*] Solar Flare Forecasting Model")
    print("=" * 60)

    # 1. Load data
    print("\n[1] Loading all lightcurve data...")
    times, counts = load_all_data()

    # 2. Load flare catalog
    print("\n[2] Loading flare catalog...")
    catalog = load_flare_catalog()
    print(f"  {len(catalog)} flares in catalog")

    # 3. Engineer features
    print("\n[3] Engineering features (30-min sliding window)...")
    X, feature_names, sample_indices = engineer_features(times, counts)
    sample_times = times[sample_indices]

    # 4. Create labels for each horizon
    print("\n[4] Creating labels...")
    for name, horizon_sec in HORIZONS.items():
        labels = create_labels(times, catalog, horizon_sec)
        y = labels[sample_indices]
        print(f"  {name}: {y.sum()} positive samples ({y.sum()/len(y)*100:.2f}%)")

    # Use primary horizon
    primary_labels = create_labels(times, catalog, HORIZONS[PRIMARY_HORIZON])
    y = primary_labels[sample_indices]

    # 5. Temporal train/val/test split
    # IMPORTANT: No random split! Use time-based split to prevent data leakage.
    print("\n[5] Splitting data (temporal split)...")
    n = len(X)
    train_end = int(n * 0.6)
    val_end = int(n * 0.8)

    X_train, y_train = X[:train_end], y[:train_end]
    X_val, y_val = X[train_end:val_end], y[train_end:val_end]
    X_test, y_test = X[val_end:], y[val_end:]
    times_test = sample_times[val_end:]

    print(f"  Train: {len(X_train)} samples (days 1-4)")
    print(f"  Val:   {len(X_val)} samples (days 5-6)")
    print(f"  Test:  {len(X_test)} samples (days 6-7)")

    # 6. Scale features
    print("\n[6] Scaling features...")
    scaler = StandardScaler()
    X_train_s = scaler.fit_transform(X_train)
    X_val_s = scaler.transform(X_val)
    X_test_s = scaler.transform(X_test)

    # 7. Train model
    print("\n[7] Training XGBoost model...")
    model = train_model(X_train_s, y_train, X_val_s, y_val, feature_names)

    # 8. Evaluate
    print("\n[8] Evaluating on test set...")

    # Find flares that fall in the test period
    test_start = times_test[0]
    test_end = times_test[-1]
    test_catalog = [f for f in catalog
                    if f["start_time"] >= test_start and f["start_time"] <= test_end]
    print(f"  Flares in test period: {len(test_catalog)}")

    results = evaluate_model(model, X_test_s, y_test, times_test, test_catalog,
                            feature_names, PRIMARY_HORIZON)

    # 9. Plot timeline
    print("\n[9] Plotting prediction timeline...")
    plot_predictions_timeline(times_test, y_test,
                            model.predict_proba(X_test_s)[:, 1],
                            test_catalog, PRIMARY_HORIZON)

    # 10. Save model
    print("\n[10] Saving model artifacts...")
    with open("forecast_model.pkl", "wb") as f:
        pickle.dump({"model": model, "scaler": scaler, "feature_names": feature_names}, f)
    print("  Saved: forecast_model.pkl")

    # Save results summary
    results["horizon"] = PRIMARY_HORIZON
    results["n_features"] = len(feature_names)
    results["feature_names"] = feature_names
    with open("forecast_results.json", "w") as f:
        json.dump(results, f, indent=2, default=str)
    print("  Saved: forecast_results.json")

    print("\n" + "=" * 60)
    print("[OK] Forecasting model complete!")
    print(f"  ROC-AUC: {results['roc_auc']:.4f}")
    print(f"  True Positive Rate: {results['tpr']:.4f}")
    print(f"  False Alarm Rate: {results['far']:.4f}")
    print("=" * 60)


if __name__ == "__main__":
    main()
